### ISSUE TITLE
Support for webpack

### ISSUE THREAD

**Issue by MattTheNub** [amazinigmech2418/mechjs#3]
It would be really useful to be able to use webpack, by doing something like creating an `index.js` with all the libraries exported. It would be really useful, as webpack is popular, and it has quite a nice syntax:
```js
import { canvasJS } from 'mechjs'

canvasJS.text.stroke('Arial', 'Hello World!', 50, 50);
```

**Comment by AmazingMech2418** [comment]
What is webpack?

**Comment by MattTheNub** [comment]
[Webpack](https://webpack.js.org/guides/getting-started/) is an easier way to manage dependencies on web-based projects

**Comment by AmazingMech2418** [comment]
OK.

**Comment by AmazingMech2418** [comment]
Could you submit a PR for it? @MegaCode18

**Comment by MattTheNub** [comment]
Sure.
